# Publish-Release.ps1
# Automates the release process for SnakeUSBIP

$version = "2.0.2"
$projectPath = "d:\REPOS_GITHUB\SnakeUSBIP-WPF\src\SnakeUSBIP"
$releasePath = "d:\REPOS_GITHUB\SnakeUSBIP-WPF\release"
$usbIdsPath = "d:\REPOS_GITHUB\SnakeUSBIP-WPF\src\SnakeUSBIP\usb.ids"
$repoRoot = "d:\REPOS_GITHUB\SnakeUSBIP-WPF"

# New folder structure (root level)
$portableX64 = "$repoRoot\Portable-X64"
$portableArm64 = "$repoRoot\Portable-ARM64"

# Inno Setup Compiler Path
$iscc = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
if (-not (Test-Path $iscc)) { $iscc = "${env:ProgramFiles}\Inno Setup 6\ISCC.exe" }

Write-Host "🚀 Starting SnakeUSBIP v$version Release Build..." -ForegroundColor Cyan

# Clean release folder
if (Test-Path $releasePath) { Remove-Item $releasePath -Recurse -Force }
New-Item -ItemType Directory -Path "$releasePath\temp_x64\Portable" | Out-Null
New-Item -ItemType Directory -Path "$releasePath\temp_arm64\Portable" | Out-Null

# ---------------------------------------------------------
# 1. Build Executables
# ---------------------------------------------------------

Write-Host "📦 Building x64..." -ForegroundColor Yellow
dotnet publish "$projectPath\SnakeUSBIP.csproj" -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o "$releasePath\temp_x64\Portable" --nologo
if ($LASTEXITCODE -ne 0) { Write-Error "Build x64 failed"; exit 1 }

Write-Host "📦 Building ARM64..." -ForegroundColor Yellow
dotnet publish "$projectPath\SnakeUSBIP.csproj" -c Release -r win-arm64 --self-contained true -p:PublishSingleFile=true -o "$releasePath\temp_arm64\Portable" --nologo
if ($LASTEXITCODE -ne 0) { Write-Error "Build ARM64 failed"; exit 1 }

# ---------------------------------------------------------
# 2. Prepare Assets
# ---------------------------------------------------------

Write-Host "📄 Copying assets..." -ForegroundColor Cyan

# Copy usb.ids
if (Test-Path $usbIdsPath) {
    Copy-Item $usbIdsPath "$releasePath\temp_x64\Portable\usb.ids" -Force
    Copy-Item $usbIdsPath "$releasePath\temp_arm64\Portable\usb.ids" -Force
}

# Helper tools (from _reference)
$helpers = @("usbipw.exe", "devnode.exe", "libusbip.dll", "resources.dll", "CleanDrivers.ps1", "Logo-SnakeFoxU-con-e.ico")
foreach ($file in $helpers) {
    $src = "$repoRoot\_reference\$file"
    if (Test-Path $src) {
        Copy-Item $src "$releasePath\temp_x64\Portable\$file" -Force
        Copy-Item $src "$releasePath\temp_arm64\Portable\$file" -Force
    }
}

# Drivers x64 (from Portable-X64/drivers)
$driversX64 = "$portableX64\drivers"
if (Test-Path $driversX64) {
    Copy-Item $driversX64 "$releasePath\temp_x64\Portable\drivers" -Recurse -Force
}

# Drivers ARM64 (from Portable-ARM64/drivers)
$driversArm64 = "$portableArm64\drivers"
if (Test-Path $driversArm64) {
    Copy-Item $driversArm64 "$releasePath\temp_arm64\Portable\drivers" -Recurse -Force
}

# License & Readme
Copy-Item "$repoRoot\LICENSE" "$releasePath\temp_x64\Portable\LICENSE" -Force
Copy-Item "$repoRoot\README.md" "$releasePath\temp_x64\Portable\README.md" -Force
Copy-Item "$repoRoot\LICENSE" "$releasePath\temp_arm64\Portable\LICENSE" -Force
Copy-Item "$repoRoot\README.md" "$releasePath\temp_arm64\Portable\README.md" -Force

# ARM64 specific README (test-signed driver warning)
$arm64Readme = "$portableArm64\README_ARM64.md"
if (Test-Path $arm64Readme) {
    Copy-Item $arm64Readme "$releasePath\temp_arm64\Portable\README_ARM64.md" -Force
}

# Wizard images for installer (copy to temp_x64 root for ISCC)
$wizardImages = @("wizard_image.bmp", "wizard_small.bmp")
foreach ($img in $wizardImages) {
    $src = "$repoRoot\_reference\$img"
    if (Test-Path $src) { Copy-Item $src "$releasePath\temp_x64\$img" -Force }
}

# Icon for installer
$iconSrc = "$repoRoot\_reference\Logo-SnakeFoxU-con-e.ico"
if (Test-Path $iconSrc) { Copy-Item $iconSrc "$releasePath\temp_x64\Logo-SnakeFoxU-con-e.ico" -Force }

# ---------------------------------------------------------
# 3. Clean unnecessary files from Portable folders
# ---------------------------------------------------------

Write-Host "🧹 Cleaning unnecessary files..." -ForegroundColor Gray

# Remove .pdb files (debug symbols)
Get-ChildItem "$releasePath\temp_x64\Portable" -Filter "*.pdb" | Remove-Item -Force
Get-ChildItem "$releasePath\temp_arm64\Portable" -Filter "*.pdb" | Remove-Item -Force

# Remove Assets folder (generated by .NET)
$assetsX64 = "$releasePath\temp_x64\Portable\Assets"
$assetsArm64 = "$releasePath\temp_arm64\Portable\Assets"
if (Test-Path $assetsX64) { Remove-Item $assetsX64 -Recurse -Force }
if (Test-Path $assetsArm64) { Remove-Item $assetsArm64 -Recurse -Force }

# ---------------------------------------------------------
# 4. Create ZIP Packages
# ---------------------------------------------------------

Write-Host "📚 Creating ZIP packages..." -ForegroundColor Magenta
$x64Zip = "$releasePath\SnakeUSBIP-v$version-x64.zip"
$arm64Zip = "$releasePath\SnakeUSBIP-v$version-arm64.zip"

Compress-Archive -Path "$releasePath\temp_x64\Portable\*" -DestinationPath $x64Zip -Force
Compress-Archive -Path "$releasePath\temp_arm64\Portable\*" -DestinationPath $arm64Zip -Force

# ---------------------------------------------------------
# 5. Create Setup Installer (x64 only)
# ---------------------------------------------------------

if (Test-Path $iscc) {
    Write-Host "💿 Compiling Setup (x64)..." -ForegroundColor Yellow
    
    # Copy LICENSE and README to temp_x64 root for ISCC
    Copy-Item "$repoRoot\LICENSE" "$releasePath\temp_x64\LICENSE" -Force
    Copy-Item "$repoRoot\README.md" "$releasePath\temp_x64\README.md" -Force
    
    $issSrc = "$repoRoot\_reference\SnakeUSBIP.iss"
    $issDest = "$releasePath\temp_x64\Setup.iss"
    
    $issContent = Get-Content $issSrc -Raw
    $issContent = $issContent -replace '#define MyAppVersion ".*?"', "#define MyAppVersion ""$version"""
    $issContent = $issContent -replace 'OutputDir=installer', "OutputDir=$releasePath"
    $issContent = $issContent -replace 'LicenseFile=LICENSE', "LicenseFile=.\LICENSE"
    $issContent = $issContent -replace 'WizardImageFile=wizard_image.bmp', "WizardImageFile=.\wizard_image.bmp"
    $issContent = $issContent -replace 'WizardSmallImageFile=wizard_small.bmp', "WizardSmallImageFile=.\wizard_small.bmp"
    
    Set-Content -Path $issDest -Value $issContent
    
    $proc = Start-Process -FilePath $iscc -ArgumentList "`"$issDest`"" -WorkingDirectory "$releasePath\temp_x64" -PassThru -NoNewWindow -Wait
    
    if ($proc.ExitCode -eq 0) { Write-Host "✅ Setup (x64) created successfully" -ForegroundColor Green }
    else { Write-Error "Setup failed (Exit: $($proc.ExitCode))" }
}
else {
    Write-Warning "⚠️ ISCC.exe not found. Skipping Installer."
}

# ---------------------------------------------------------
# 6. Summary
# ---------------------------------------------------------

Write-Host ""
Write-Host "✅ Release Build Complete!" -ForegroundColor Green
Write-Host "   ZIP x64:    $x64Zip"
Write-Host "   ZIP ARM64:  $arm64Zip"
Write-Host "   Setup x64:  $releasePath\SnakeUSBIP_Setup_v$version.exe"
